### ISSUE TITLE
기사 작성 Editor

### ISSUE THREAD

**Issue by yoonhok524** [hppk-journalist-2019/HPPK-Robo-Cup-2019#3]
기사 작성에 유용한 Editor 라이브러리 조사

1. [vue-quill-editor](https://github.com/surmon-china/vue-quill-editor)
1. [tiptap](https://github.com/scrumpy/tiptap)

tiptap이 좀더 인기가 많은 듯

그 외 [여기](https://github.com/vuejs/awesome-vue#rich-text-editing)에 다양한 라이브러리가 있으니 참고!

**Comment by silarrow** [comment]
vuetify Icon 목록 
https://material.io/tools/icons/?style=baseline

**Comment by yoonhok524** [comment]
Web쪽에서는 fontawesome 아이콘도 많이 쓰는 듯
https://fontawesome.com/icons?from=io
