### ISSUE TITLE
News 컨텐츠 크기 1MB 제한으로 인해 업로드 실패하는 문제

### ISSUE THREAD

**Issue by yoonhok524** [hppk-journalist-2019/HPPK-Robo-Cup-2019#55]
아래 공식 문서 참고
> Maximum size for a document | 1 MiB (1,048,576 bytes)
> https://firebase.google.com/docs/firestore/quotas#collections_documents_and_fields

**Comment by silarrow** [comment]
Image를 기존 Base64 데이터를 그대로 저장하던 방법에서 Storage에 올린 후 링크로 대체하도록 변경
